### ISSUE TITLE
Performance optimizations by avoiding builders and using standard lib functions

### ISSUE THREAD

**Issue by teenriot** [daniel-rusu/pods4k#7]
I may found some significant optimizations. I only looked at reference arrays and this is not complete. In general there are several places where builders with capacity checks could be avoided and where standard kotlin functions are faster than the current implementations. I benchmarked with kotlinx-benchmark against the benchmark scenario you use.

Around 14% performance gain:
```
public operator fun <T> ImmutableArray<T>.plus(other: ImmutableArray<T>): ImmutableArray<T> =
    when {
        isEmpty() -> other
        other.isEmpty() -> this
        else -> ImmutableArray((values as Array<T>) + other.values)
    }

vs

public operator fun <T> ImmutableArray<T>.plus(other: ImmutableArray<T>): ImmutableArray<T> {
    when {
        isEmpty() -> return other
        other.isEmpty() -> return this
    }
    return buildImmutableArray(initialCapacity = size + other.size) {
        addAll(this@plus)
        addAll(other)
    }
}
```

Around 32% performance gain:
```
public operator fun <T> ImmutableArray<T>.plus(element: T): ImmutableArray<T> =
    ImmutableArray((values as Array<T>) + element)

vs

public operator fun <T> ImmutableArray<T>.plus(element: T): ImmutableArray<T> =
    buildImmutableArray(initialCapacity = size + 1) {
        addAll(this@plus)
        add(element)
    }

```

A third example is shared [here](https://github.com/daniel-rusu/pods4k/pull/3#issuecomment-2557904056). 

(I don't create a pull request since i'm not experienced enough)

**Comment by daniel-rusu** [comment]
@teenriot thanks so much for this suggestion!  I added both of these efficiency improvements for all 9 Immutable Array types and these will be included in the next release.
